### ISSUE TITLE
Unknown usb Device found

### ISSUE THREAD

**Issue by AKASHWORLD614** [khairulhasanmd/USBaspLoader-Atmega32#1]
i have programmed my atmega32 with your code and set the fuses right then i have plugged my atmega32 to which i connected few resistors and diodes and connected it is recognized as unknown device with VID and PID as 0000 how do i resolve this error please help fast

**Comment by khairulhasanmd** [comment]
Hello..
Sorry for my late response for a busy schedule.
You need to make sure of the following things : 
1. The zener diode voltage and resistors and their connection must be same as shown in the vusb https://www.fischl.de/usbasp/bilder/usbasp_circuit.png diagram.
2. After flashing, You have to set the fusebits as hfuse:0xd8  lfuse:0xcf 
3. You have to set the lock bits as : lock:0xef

I think that's all. The most problem i had, with the zener diodes and their connections.
the final device looks like this for me : https://khairulhasanmd.wordpress.com/category/usbasploader-2/
You can find more explanation there too. Try to debug according to the information provided there.

And yes, let me know if you have succeed or struggling with another problem.
Thanks.

**Comment by AKASHWORLD614** [comment]
i connected zener diodes of 3.6v and resistors of 68 ohm and pull up resistor of 1.5k 1/2w and D+ and D- are connected PD2 and PD4
i set the fusebits correctly and it shows fuse bit verified and shows the fusebits of what i programmed
when i set lock fuse bit 0xEF it says that it is not there in datasheet try 0x2f so this was the error i got 

can you compile for me script with 16mhz crystal and ATmega32 and send me the hex file i am having issues compiling the thing which version of avrdude are you using?

**Comment by AKASHWORLD614** [comment]
i connected zener diodes of 3.6v and resistors of 68 ohm and pull up resistor of 1.5k 1/2w and D+ and D- are connected PD2 and PD4
i set the fusebits correctly and it shows fuse bit verified and shows the fusebits of what i programmed
when i set lock fuse bit 0xEF it says that it is not there in datasheet try 0x2f so this was the error i got

can you compile for me script with 16mhz crystal and ATmega32 with D+ on PD2 and D- on PD4 
please send me the hex file i am having issues compiling the thing which version of avrdude are you using?

**Comment by khairulhasanmd** [comment]
I will update the documentation. I have recently checked the codes and tested the circuit. 
Jumper to ground(programming mode): PD0
USB D- : PD1
USB D+ : PD2
Change your pins in your board. It should work.
